### ISSUE TITLE
Can't compile with SDL2 2.0.14 from LMDE5

### ISSUE THREAD

**Issue by guest123guest** [andreas-jonsson/virtualxt#47]
```
front/sdl/mu_renderer.c: In function ‘flush’:
front/sdl/mu_renderer.c:90:2: error: implicit declaration of function ‘SDL_RenderGeometryRaw’; did you mean ‘SDL_RenderGetMetalLayer’? [-Werror=implicit-function-declaration]
   90 |  SDL_RenderGeometryRaw(r->renderer, r->texture,
      |  ^~~~~~~~~~~~~~~~~~~~~
      |  SDL_RenderGetMetalLayer
cc1: all warnings being treated as errors
make[1]: *** [sdl2-frontend.make:182: obj/native/release/sdl2-frontend/mu_renderer.o] Error 1
make: *** [Makefile:286: sdl2-frontend] Error 2
```
I get this error when following the instructions from README, what should I do to get a newer version of SDL that has this instruction? Is there a fallback or will I have to compile the web frontend?

**Comment by andreas-jonsson** [comment]
Hi

Yes. you need SDL 2.0.20 or newer. (Released in Jan 2022)
You either need to build SDL from source or download a prebuilt update for your system.

Unfortunately there is no fallback to other APIs. 
But you could try the Web or Libretro version.

Web:
```
premake5 --modules=ctrl --static gmake
make config=release_web clean web-frontend
```

Libretro:
```
premake5 gmake
make clean libretro-frontend
```

**Comment by andreas-jonsson** [comment]
If you just want to test run the emulator. Perhaps the Flatpak version is an option? It has just been updated to the latest version. https://flathub.org/apps/org.virtualxt.VirtualXT

**Comment by guest123guest** [comment]
I compiled a newer version of SDL2 and the emulator now compiles and runs. However, when I decided to run 8088MPH (For fun, I'm sure your emulator would never be accurate enough and there seems to be no composite option anyway.), it says that the CPU runs between 1000% and 3000% faster than a real 8088, even when I set it to run in 8088 mode rather than V20 mode. Trying to run the demo shows nothing, not even a black and white picture like DOSBOX would.

**Comment by andreas-jonsson** [comment]
Well.. you wont be running either 8088MPH or Area5150 on VirtualXT unfortunately. It requires very precise timing and near perfect CGA emulation and they target the original IBM 5150 explicitly. That is currently not the goal for this emulator. If you want to try out these demos on an emulator I recommend @dbalsom (GloriousCow) [MartyPC](https://github.com/dbalsom/martypc) whose main focus is accuracy.

As for the reported speed. That is a bit strange. I have to look in to that. I would not expect it to be 100% but I don't see why it should be that far off.

Composite output is being worked on and might be part of next release.
